# Generated by Django 6.0.1 on 2026-04-16 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('source', models.CharField(default='twitter', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('brand_keyword', models.CharField(blank=True, max_length=100, null=True)),
                ('original_sentiment', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'social_media_posts',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SentimentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], max_length=20)),
                ('confidence', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentiments', to='api.socialmediapost')),
            ],
            options={
                'db_table': 'sentiment_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment_category', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], max_length=20)),
                ('keyword', models.CharField(max_length=100)),
                ('frequency', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'themes',
                'ordering': ['-frequency'],
                'unique_together': {('sentiment_category', 'keyword')},
            },
        ),
    ]
